---
- hosts: elis
  become: yes
  tasks:
  - name: Create elis-user account on servers
    user:
      name: 'elis-user'
      comment: 'ELIS Team User'
      groups: 'wheel'
      append: 'yes'
      shell: '/bin/bash'

  - name: Add authorized keys
    authorized_key:
      user: elis-user
      state: 'present'
      key: "{{ lookup('file', '/home/elis-user/.ssh/id_rsa.pub') }}"

#key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
