---
- hosts: "elis"
  become: yes
  vars:
    users:
    -  "elis-user"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "wheel"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
