---
- hosts: elis
  become: yes
  vars:
    users:
    - elis-user
  tasks:
  - name: Create elis-user account on servers
    user:
      name: 'elis-user'
      comment: 'ELIS Team User'
      groups: 'wheel'
      append: 'yes'
      shell: '/bin/bash'

  - name: Add authorized keys
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}" 
      with_items: "{{ users }}"
