---
- hosts: elis
  become: yes
  tasks:
  - name: Create elis-user account on servers
    user:
      name: 'elis-user'
      comment: 'ELIS Team User'
      groups: 'wheel'
      append: 'yes'
      shell: '/bin/bash'

  - name: Creates directory
    file:
      path: '/home/elis-user/.ssh'
      state: 'directory'
      owner: 'elis-user'
      group: 'elis-user'
      mode: 0644
      
  - name: Add authorized keys
    authorized_key:
      user: 'elis-user'
      key: "{{ lookup('file', '/home/elis-user/.ssh/id_rsa.pub') }}"
      state: 'present'
